/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "main.h"
#include "stdlib.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END
#define With  48
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "SetOfs", ID_WINDOW_SET, 1, 0, 794, 440, 0, 0x0, 0 },
  
  { BUTTON_CreateIndirect, "1", ID_BUTTON_SET1, 458,  40, 80, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "2", ID_BUTTON_SET2, 562,  40, 80, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "3", ID_BUTTON_SET3, 665,  40, 80, 60, 0, 0x0, 0 },
  
  { BUTTON_CreateIndirect, "4", ID_BUTTON_SET4, 458,  118, 80, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "5", ID_BUTTON_SET5, 562,  118, 80, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "6", ID_BUTTON_SET6, 665,  118, 80, 60, 0, 0x0, 0 },
  
  { BUTTON_CreateIndirect, "7", ID_BUTTON_SET7, 458,  199, 80, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "8", ID_BUTTON_SET8, 562,  199, 80, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "9", ID_BUTTON_SET9, 665,  199, 80, 60, 0, 0x0, 0 },
  
  { BUTTON_CreateIndirect, "0", ID_BUTTON_SET0,       562, 280, 80, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Delete", ID_BUTTON_SET10, 665, 280, 80, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Back", ID_BUTTON_SET11,   458, 280, 80, 60, 0, 0x0, 0 },
  
  { BUTTON_CreateIndirect, "OK",  ID_BUTTON_OK,    458, 358, 287, 50, 0, 0x0, 0 },
 
  
  { TEXT_CreateIndirect, "ET_Z:", ID_TEXT_TITLE0, 40, 18+0*With, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "CH_1:", ID_TEXT_TITLE1, 40, 18+1*With, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "CH_2:", ID_TEXT_TITLE2, 40, 18+2*With, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "CH_3:", ID_TEXT_TITLE3, 40, 18+3*With, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "CH_4:", ID_TEXT_TITLE4, 40, 18+4*With, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "CH_5:", ID_TEXT_TITLE5, 40, 18+5*With, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "CH_6:", ID_TEXT_TITLE6, 40, 18+6*With, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "CH_7:", ID_TEXT_TITLE7, 40, 18+7*With, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "CH_8:", ID_TEXT_TITLE8, 40, 18+8*With, 60, 30, 0, 0x0, 0 },
  
  { EDIT_CreateIndirect, "Edit", ID_EDIT_SET0,  100, 15+0*With, 85, 26, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_SET1,  100, 15+1*With, 85, 26, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_SET2,  100, 15+2*With, 85, 26, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_SET3,  100, 15+3*With, 85, 26, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_SET4,  100, 15+4*With, 85, 26, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_SET5,  100, 15+5*With, 85, 26, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_SET6,  100, 15+6*With, 85, 26, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_SET7,  100, 15+7*With, 85, 26, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_SET8,  100, 15+8*With, 85, 26, 0, 0x64, 0 },
  
  { TEXT_CreateIndirect, "0", ID_TEXT_SETPV0,   238, 15+0*With, 85, 26, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0", ID_TEXT_SETPV1,   238, 15+1*With, 85, 26, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0", ID_TEXT_SETPV2,   238, 15+2*With, 85, 26, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0", ID_TEXT_SETPV3,   238, 15+3*With, 85, 26, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0", ID_TEXT_SETPV4,   238, 15+4*With, 85, 26, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0", ID_TEXT_SETPV5,   238, 15+5*With, 85, 26, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0", ID_TEXT_SETPV6,   238, 15+6*With, 85, 26, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0", ID_TEXT_SETPV7,   238, 15+7*With, 85, 26, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0", ID_TEXT_SETPV8,   238, 15+8*With, 85, 26, 0, 0x0, 0 },
  
  { TEXT_CreateIndirect, "EV:", ID_TEXT_TXTPV0,   209, 18+0*With, 27, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "PV:", ID_TEXT_TXTPV1,   209, 18+1*With, 27, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "PV:", ID_TEXT_TXTPV2,   209, 18+2*With, 27, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "PV:", ID_TEXT_TXTPV3,   209, 18+3*With, 27, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "PV:", ID_TEXT_TXTPV4,   209, 18+4*With, 27, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "PV:", ID_TEXT_TXTPV5,   209, 18+5*With, 27, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "PV:", ID_TEXT_TXTPV6,   209, 18+6*With, 27, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "PV:", ID_TEXT_TXTPV7,   209, 18+7*With, 27, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "PV:", ID_TEXT_TXTPV8,   209, 18+8*With, 27, 20, 0, 0x0, 0 },
  
  { RADIO_CreateIndirect, "Radio1", ID_RADIO_SET0, 328, 8+1*With, 67, 39, 0, 0x1402, 0 },  
  { RADIO_CreateIndirect, "Radio1", ID_RADIO_SET1, 328, 8+2*With, 67, 39, 0, 0x1402, 0 }, 
  { RADIO_CreateIndirect, "Radio1", ID_RADIO_SET2, 328, 8+3*With, 67, 39, 0, 0x1402, 0 }, 
  { RADIO_CreateIndirect, "Radio1", ID_RADIO_SET3, 328, 8+4*With, 67, 39, 0, 0x1402, 0 }, 
  { RADIO_CreateIndirect, "Radio1", ID_RADIO_SET4, 328, 8+5*With, 67, 39, 0, 0x1402, 0 }, 
  { RADIO_CreateIndirect, "Radio1", ID_RADIO_SET5, 328, 8+6*With, 67, 39, 0, 0x1402, 0 }, 
  { RADIO_CreateIndirect, "Radio1", ID_RADIO_SET6, 328, 8+7*With, 67, 39, 0, 0x1402, 0 }, 
  { RADIO_CreateIndirect, "Radio1", ID_RADIO_SET7, 328, 8+8*With, 67, 39, 0, 0x1402, 0 }, 
	
 
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END
extern void TemperaturePV(WM_HWIN hItem,int Item,int id);
extern uint16_t HTofs[9];
char* intToText(int data)
{
	static char str[4];
	str[0]=(char)(data/1000%10)+0x30;
	str[1]=(char)(data/100%10)+0x30;
	str[2]=(char)(data/10%10)+0x30;
	str[3]=(char)(data%10)+0x30;
	
	while(1){
		if(str[0] =='0'){
			str[0] = str[1];
			str[1] = str[2];
			str[2] = str[3];
			str[3] = '\0';
		}
		else {
			break;
		}
	}
	return str;
}
/*********************************************************************
*
*       _cbDialog
*/
extern uint16_t Env;
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  static int hEdi,fig=0;
  char str[10];	
  int i,j;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, 0x00FFFFFF);
   
	 for(j=0,i=ID_EDIT_SET1; i<=ID_EDIT_SET8; i++,j++) {
		  hItem = WM_GetDialogItem(pMsg->hWin, i);	 
        EDIT_SetFont(hItem, GUI_FONT_24_ASCII);			 
		  EDIT_SetText(hItem, intToText(HTofs[j]));
		  EDIT_SetMaxLen(hItem,4);
	 }
	 hEdi = ID_EDIT_SET0; fig = 0;
	 hItem = WM_GetDialogItem(pMsg->hWin, hEdi);
	 EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
	 EDIT_SetText(hItem, intToText(HTofs[8]));
	 EDIT_SetMaxLen(hItem,4);
	 
	 for(i=ID_TEXT_TITLE0; i<=ID_TEXT_TITLE8; i++) {
		  hItem = WM_GetDialogItem(pMsg->hWin, i); 
        TEXT_SetFont(hItem, GUI_FONT_16_ASCII);
	 }
   
    for(i=ID_TEXT_TXTPV0; i<=ID_TEXT_TXTPV8; i++) {
		  hItem = WM_GetDialogItem(pMsg->hWin, i); 
        TEXT_SetFont(hItem, GUI_FONT_16_ASCII);
	 }
   
	 for(i=ID_TEXT_SETPV0; i<=ID_TEXT_SETPV8; i++) {
		  hItem = WM_GetDialogItem(pMsg->hWin, i); 
        TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
	 }
    
	for(j=0,i=ID_RADIO_SET0; i<=ID_RADIO_SET7; i++,j++) {
		hItem = WM_GetDialogItem(pMsg->hWin, i);
      RADIO_SetFont(hItem, GUI_FONT_16_ASCII);
      RADIO_SetText(hItem, "J type", 1);
      RADIO_SetText(hItem, "K type", 0);
	   RADIO_SetValue(hItem,temperature[j].jk); 
	}
    
   
  
	 for(i=ID_BUTTON_SET0; i<=ID_BUTTON_SET11; i++) {
			hItem = WM_GetDialogItem(pMsg->hWin, i);			
			BUTTON_SetFont(hItem, GUI_FONT_24B_ASCII);
			BUTTON_SetFocussable(hItem, 0); 
	   }
  
   hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_OK);	
	BUTTON_SetFont(hItem, GUI_FONT_24B_ASCII);
	BUTTON_SetFocussable(hItem, 0); 			
	 
   break;
  case WM_DELETE:
	  if(fig == 1){
		  fig = 0;
		  for(j=0,i=ID_EDIT_SET1; i<=ID_EDIT_SET8; i++,j++){
				hItem = WM_GetDialogItem(pMsg->hWin, i);				
				EDIT_GetText(hItem,str,5); 
				HTofs[j] = atoi(str);								
		  }
		  hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_SET0);				
		  EDIT_GetText(hItem,str,5); 
		  HTofs[8] = atoi(str);
		  OFSchang();		  
	  }
    	  
	  break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    char acBuffer[10];
	   int Key;
    switch(Id) {
//----------------------------------------------------
    case ID_EDIT_SET0: // Notifications sent by 'ET'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
       hEdi = ID_EDIT_SET0; fig = 1;
        break;    
      }
      break;
    case ID_EDIT_SET1: 
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
      hEdi = ID_EDIT_SET1; fig = 1;
        break;
      }
      break;
	case ID_EDIT_SET2: 
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
      hEdi = ID_EDIT_SET2; fig = 1;
        break;
      }
      break;
	case ID_EDIT_SET3: 
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
      hEdi = ID_EDIT_SET3; fig = 1;
        break;
      }
      break;
	case ID_EDIT_SET4: 
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
      hEdi = ID_EDIT_SET4; fig = 1;
        break;
      }
      break;
	case ID_EDIT_SET5: 
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
      hEdi = ID_EDIT_SET5; fig = 1;
        break;
      }
      break;
	case ID_EDIT_SET6: 
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
      hEdi = ID_EDIT_SET6; fig = 1;
        break;
      }
      break;
	case ID_EDIT_SET7: 
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
      hEdi = ID_EDIT_SET7; fig = 1;
        break;
      }
      break;
	case ID_EDIT_SET8: 
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
      hEdi = ID_EDIT_SET8; fig = 1;
        break;
      }
      break;
//----------------------------------------------------
    case ID_RADIO_SET0: // Notifications sent by 'Radio1'
      switch(NCode) {
      case WM_NOTIFICATION_VALUE_CHANGED:
         JKchang(0,RADIO_GetValue(WM_GetDialogItem(pMsg->hWin, ID_RADIO_SET0)));			
        break;    
      }
      break;
	case ID_RADIO_SET1: // Notifications sent by 'Radio2'
      switch(NCode) {
      case WM_NOTIFICATION_VALUE_CHANGED:
        JKchang(1,RADIO_GetValue(WM_GetDialogItem(pMsg->hWin, ID_RADIO_SET1)));	
        break;    
      }
      break;
	case ID_RADIO_SET2: // Notifications sent by 'Radio3'
      switch(NCode) {
      case WM_NOTIFICATION_VALUE_CHANGED:
        JKchang(2,RADIO_GetValue(WM_GetDialogItem(pMsg->hWin, ID_RADIO_SET2)));	
        break;    
      }
      break;
   case ID_RADIO_SET3: // Notifications sent by 'Radio4'
      switch(NCode) {
      case WM_NOTIFICATION_VALUE_CHANGED:
        JKchang(3,RADIO_GetValue(WM_GetDialogItem(pMsg->hWin, ID_RADIO_SET3)));	
        break;    
      }
      break;
	case ID_RADIO_SET4: // Notifications sent by 'Radio5'
      switch(NCode) {
      case WM_NOTIFICATION_VALUE_CHANGED:
        JKchang(4,RADIO_GetValue(WM_GetDialogItem(pMsg->hWin, ID_RADIO_SET4)));	
        break;    
      }
      break;
	case ID_RADIO_SET5: // Notifications sent by 'Radio6'
      switch(NCode) {
      case WM_NOTIFICATION_VALUE_CHANGED:
       JKchang(5,RADIO_GetValue(WM_GetDialogItem(pMsg->hWin, ID_RADIO_SET5)));	
        break;    
      }
		break;
	case ID_RADIO_SET6: // Notifications sent by 'Radio7'
      switch(NCode) {
      case WM_NOTIFICATION_VALUE_CHANGED:
        JKchang(6,RADIO_GetValue(WM_GetDialogItem(pMsg->hWin, ID_RADIO_SET6)));	
        break;    
      }
      break;
	case ID_RADIO_SET7: // Notifications sent by 'Radio8'
      switch(NCode) {
      case WM_NOTIFICATION_VALUE_CHANGED:
        JKchang(7,RADIO_GetValue(WM_GetDialogItem(pMsg->hWin, ID_RADIO_SET7)));	
        break;    
      }
      break;
//---------------------------------------------------
    case ID_BUTTON_SET0: // Notifications sent by '0'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
			 BUTTON_GetText(pMsg->hWinSrc, acBuffer, sizeof(acBuffer)); 
		    Key = acBuffer[0];
		    GUI_SendKeyMsg(Key, 1);
        break;     
      }
      break;
    case ID_BUTTON_SET1: // Notifications sent by '1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
         BUTTON_GetText(pMsg->hWinSrc, acBuffer, sizeof(acBuffer)); 
		    Key = acBuffer[0];
		    GUI_SendKeyMsg(Key, 1);
        break;    
      }
      break;
    case ID_BUTTON_SET2: // Notifications sent by '2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
         BUTTON_GetText(pMsg->hWinSrc, acBuffer, sizeof(acBuffer)); 
		    Key = acBuffer[0];
		    GUI_SendKeyMsg(Key, 1);
        break;
      }
      break;
    case ID_BUTTON_SET3: // Notifications sent by '3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
         BUTTON_GetText(pMsg->hWinSrc, acBuffer, sizeof(acBuffer)); 
		    Key = acBuffer[0];
		    GUI_SendKeyMsg(Key, 1);
        break;
      }
      break;
    case ID_BUTTON_SET4: // Notifications sent by '4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        BUTTON_GetText(pMsg->hWinSrc, acBuffer, sizeof(acBuffer)); 
		    Key = acBuffer[0];
		    GUI_SendKeyMsg(Key, 1);
        break;
      }
      break;
    case ID_BUTTON_SET5: // Notifications sent by '5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        BUTTON_GetText(pMsg->hWinSrc, acBuffer, sizeof(acBuffer)); 
		    Key = acBuffer[0];
		    GUI_SendKeyMsg(Key, 1);
        break;
      }
      break;
    case ID_BUTTON_SET6: // Notifications sent by '6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
         BUTTON_GetText(pMsg->hWinSrc, acBuffer, sizeof(acBuffer)); 
		    Key = acBuffer[0];
		    GUI_SendKeyMsg(Key, 1);
        break;
      }
      break;
    case ID_BUTTON_SET7: // Notifications sent by '7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
         BUTTON_GetText(pMsg->hWinSrc, acBuffer, sizeof(acBuffer)); 
		    Key = acBuffer[0];
		    GUI_SendKeyMsg(Key, 1);
        break;
      }
      break;
    case ID_BUTTON_SET8: // Notifications sent by '8'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
         BUTTON_GetText(pMsg->hWinSrc, acBuffer, sizeof(acBuffer)); 
		    Key = acBuffer[0];
		    GUI_SendKeyMsg(Key, 1);
        break;
      }
      break;
    case ID_BUTTON_SET9: // Notifications sent by '9'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
         BUTTON_GetText(pMsg->hWinSrc, acBuffer, sizeof(acBuffer)); 
		    Key = acBuffer[0];
		    GUI_SendKeyMsg(Key, 1);
        break;
      }
      break;
    case ID_BUTTON_SET10: // Notifications sent by 'DELETE'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:					
			if(hEdi != 0){
				hItem = WM_GetDialogItem(pMsg->hWin, hEdi);
				EDIT_SetText(hItem,""); 
			}
        break;
      }
      break;
    case ID_BUTTON_SET11: // Notifications sent by 'Back'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        Key = GUI_KEY_BACKSPACE;
		  GUI_SendKeyMsg(Key, 1);
        break;
      }
      break;
	 case ID_BUTTON_OK: // Notifications sent by 'OK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:			
			if(hEdi != 0) {
				hItem = WM_GetDialogItem(pMsg->hWin, hEdi);
				EDIT_GetText(hItem,str,5);
            if(hEdi == ID_EDIT_SET0)				
               HTofs[8] = atoi(str);	
				else
					HTofs[hEdi-ID_EDIT_SET1] = atoi(str);	
			}
        break;
      }
      break;

		
    }
    break;
  // USER START (Optionally insert additional message handling)
  case UPDATA_DLG:
     hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SETPV0);
	  TEXT_SetText(hItem, int2Text(Env)); 
	  TemperaturePV(pMsg->hWin,ID_TEXT_SETPV1,0);
     TemperaturePV(pMsg->hWin,ID_TEXT_SETPV2,1);
     TemperaturePV(pMsg->hWin,ID_TEXT_SETPV3,2);
     TemperaturePV(pMsg->hWin,ID_TEXT_SETPV4,3);
     TemperaturePV(pMsg->hWin,ID_TEXT_SETPV5,4);
     TemperaturePV(pMsg->hWin,ID_TEXT_SETPV6,5);
     TemperaturePV(pMsg->hWin,ID_TEXT_SETPV7,6);
     TemperaturePV(pMsg->hWin,ID_TEXT_SETPV8,7);  
	  break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSetOfs
*/

void CreateSetOfs(void) {
//  WM_HWIN hWin;

  hSeting =GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_GetClientWindow(Frame._hFrame), 0, 0);
  
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
