/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Frame", ID_FRAMEWIN, 0, 0, 720, 480, 0, 0x0, 0 },
  
  { TEXT_CreateIndirect, "id",    ID_TEXT_A0, 60, 13+7, 58, 26, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "pvVal", ID_EDIT_A0, 13, 42+7, 151, 63, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "pvVal", ID_TEXT_A4, 13, 42+7, 151, 63, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "PV",    ID_TEXT_A1, 18, 47+7, 23, 17, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "pt",    ID_TEXT_A2, 147, 68+7, 17, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "o",     ID_TEXT_A3, 145, 62+7, 8, 14, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "svVal", ID_EDIT_A1, 13, 118+7, 151, 40, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "jk", ID_BUTTON_A, 13, 170+7, 151, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SV",    ID_TEXT_A5, 16, 120+7, 21, 17, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "o",     ID_TEXT_A6, 127, 122+7, 13, 12, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "pt",    ID_TEXT_A7, 129, 128+7, 17, 20, 0, 0x64, 0 },
  
  { TEXT_CreateIndirect, "id",    ID_TEXT_B0, 60+176, 13+7, 58, 26, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "pvVal", ID_EDIT_B0, 13+176, 42+7, 151, 63, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "pvVal", ID_TEXT_B4, 13+176, 42+7, 151, 63, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "PV",    ID_TEXT_B1, 18+176, 47+7, 23, 17, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "pt",    ID_TEXT_B2, 147+176, 68+7, 17, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "o",     ID_TEXT_B3, 145+176, 62+7, 8, 14, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "svVal", ID_EDIT_B1, 13+176, 118+7, 151, 40, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "jk", ID_BUTTON_B, 13+176, 170+7, 151, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SV",    ID_TEXT_B5, 16+176, 120+7, 21, 17, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "o",     ID_TEXT_B6, 127+176, 122+7, 13, 12, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "pt",    ID_TEXT_B7, 129+176, 128+7, 17, 20, 0, 0x64, 0 },
  
  { TEXT_CreateIndirect, "id",    ID_TEXT_C0, 60+354, 13+7, 58, 26, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "pvVal", ID_EDIT_C0, 13+354, 42+7, 151, 63, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "pvVal", ID_TEXT_C4, 13+354, 42+7, 151, 63, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "PV",    ID_TEXT_C1, 18+354, 47+7, 23, 17, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "pt",    ID_TEXT_C2, 147+354, 68+7, 17, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "o",     ID_TEXT_C3, 145+354, 62+7, 8, 14, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "svVal", ID_EDIT_C1, 13+354, 118+7, 151, 40, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "jk", ID_BUTTON_C, 13+354, 170+7, 151, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SV",    ID_TEXT_C5, 16+354, 120+7, 21, 17, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "o",     ID_TEXT_C6, 127+354, 122+7, 13, 12, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "pt",    ID_TEXT_C7, 129+354, 128+7, 17, 20, 0, 0x64, 0 },
  
  { TEXT_CreateIndirect, "id",    ID_TEXT_D0, 60+532, 13+7, 58, 26, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "pvVal", ID_EDIT_D0, 13+532, 42+7, 151, 63, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "pvVal", ID_TEXT_D4, 13+532, 42+7, 151, 63, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "PV",    ID_TEXT_D1, 18+532, 47+7, 23, 17, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "pt",    ID_TEXT_D2, 147+532, 68+7, 17, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "o",     ID_TEXT_D3, 145+532, 62+7, 8, 14, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "svVal", ID_EDIT_D1, 13+532, 118+7, 151, 40, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "jk", ID_BUTTON_D, 13+532, 170+7, 151, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SV",    ID_TEXT_D5, 16+532, 120+7, 21, 17, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "o",     ID_TEXT_D6, 127+532, 122+7, 13, 12, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "pt",    ID_TEXT_D7, 129+532, 128+7, 17, 20, 0, 0x64, 0 },
  
  { TEXT_CreateIndirect, "id",    ID_TEXT_E0, 60, 13+223, 58, 26, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "pvVal", ID_EDIT_E0, 13, 42+223, 151, 63, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "pvVal", ID_TEXT_E4, 13, 42+223, 151, 63, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "PV",    ID_TEXT_E1, 18, 47+223, 23, 17, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "pt",    ID_TEXT_E2, 147, 68+223, 17, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "o",     ID_TEXT_E3, 145, 62+223, 8, 14, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "svVal", ID_EDIT_E1, 13, 118+223, 151, 40, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "jk", ID_BUTTON_E, 13, 170+223, 151, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SV",    ID_TEXT_E5, 16, 120+223, 21, 17, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "o",     ID_TEXT_E6, 127, 122+223, 13, 12, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "pt",    ID_TEXT_E7, 129, 128+223, 17, 20, 0, 0x64, 0 },
  
  { TEXT_CreateIndirect, "id",    ID_TEXT_F0, 60+176, 13+223, 58, 26, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "pvVal", ID_EDIT_F0, 13+176, 42+223, 151, 63, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "pvVal", ID_TEXT_F4, 13+176, 42+223, 151, 63, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "PV",    ID_TEXT_F1, 18+176, 47+223, 23, 17, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "pt",    ID_TEXT_F2, 147+176, 68+223, 17, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "o",     ID_TEXT_F3, 145+176, 62+223, 8, 14, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "svVal", ID_EDIT_F1, 13+176, 118+223, 151, 40, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "jk", ID_BUTTON_F, 13+176, 170+223, 151, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SV",    ID_TEXT_F5, 16+176, 120+223, 21, 17, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "o",     ID_TEXT_F6, 127+176, 122+223, 13, 12, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "pt",    ID_TEXT_F7, 129+176, 128+223, 17, 20, 0, 0x64, 0 },
  
  { TEXT_CreateIndirect, "id",    ID_TEXT_G0, 60+354, 13+223, 58, 26, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "pvVal", ID_EDIT_G0, 13+354, 42+223, 151, 63, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "pvVal", ID_TEXT_G4, 13+354, 42+223, 151, 63, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "PV",    ID_TEXT_G1, 18+354, 47+223, 23, 17, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "pt",    ID_TEXT_G2, 147+354, 68+223, 17, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "o",     ID_TEXT_G3, 145+354, 62+223, 8, 14, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "svVal", ID_EDIT_G1, 13+354, 118+223, 151, 40, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "jk", ID_BUTTON_G, 13+354, 170+223, 151, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SV",    ID_TEXT_G5, 16+354, 120+223, 21, 17, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "o",     ID_TEXT_G6, 127+354, 122+223, 13, 12, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "pt",    ID_TEXT_G7, 129+354, 128+223, 17, 20, 0, 0x64, 0 },
  
  { TEXT_CreateIndirect, "id",    ID_TEXT_H0, 60+532, 13+223, 58, 26, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "pvVal", ID_EDIT_H0, 13+532, 42+223, 151, 63, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "pvVal", ID_TEXT_H4, 13+532, 42+223, 151, 63, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "PV",    ID_TEXT_H1, 18+532, 47+223, 23, 17, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "pt",    ID_TEXT_H2, 147+532, 68+223, 17, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "o",     ID_TEXT_H3, 145+532, 62+223, 8, 14, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "svVal", ID_EDIT_H1, 13+532, 118+223, 151, 40, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "jk", ID_BUTTON_H, 13+532, 170+223, 151, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SV",    ID_TEXT_H5, 16+532, 120+223, 21, 17, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "o",     ID_TEXT_H6, 127+532, 122+223, 13, 12, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "pt",    ID_TEXT_H7, 129+532, 128+223, 17, 20, 0, 0x64, 0 },
  
};
//--------------------------------------------------------------------
//static const GUI_WIDGET_CREATE_INFO _aDialogCreate1[] = {
// { WINDOW_CreateIndirect, "panel", 0, 0, 0, 166, 196, 0, 0x0, 0 },
//  
//};
/*
//--------------------------------------------------------------------
static const GUI_WIDGET_CREATE_INFO _aDialogCreate2[] = {
  { WINDOW_CreateIndirect,    "Dialog 2", 0, 5, 37,  710, 438, FRAMEWIN_CF_MOVEABLE },
  { BUTTON_CreateIndirect,   "ButKEY", ID_BUTTON_2DLG_0, 98, 149, 45, 40, 0, 0x0, 0 },
};
//--------------------------------------------------------------------
static const GUI_WIDGET_CREATE_INFO _aDialogCreate3[] = {
  { WINDOW_CreateIndirect,    "Dialog 3", 0, 5, 37,  710, 438, FRAMEWIN_CF_MOVEABLE },
  { EDIT_CreateIndirect,   "Text", ID_EDIT_TEXT0, 1, 2, 155, 61, 0, 0x64, 0 },
};
//--------------------------------------------------------------------
static const GUI_WIDGET_CREATE_INFO _aDialogCreate4[] = {
  { WINDOW_CreateIndirect,    "Dialog 4", 0, 5, 37,  710, 438, FRAMEWIN_CF_MOVEABLE },
  
};*/
/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END
//---------------------------------------------------------------------
//static void _cbDialog1(WM_MESSAGE * pMsg) {
//  WM_HWIN hDlg;

//  hDlg = pMsg->hWin;
//  switch (pMsg->MsgId) {
//  case WM_PAINT:
//	  
//    break;
//  case WM_INIT_DIALOG:
//    hDlg = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
//    GRAPH_SetBorder(hDlg, 50, 0, 0, 0);
//    break;
//  
//  default:
//    WM_DefaultProc(pMsg);
//  }
//}
//---------------------------------------------------------------------
//static void _cbDialog2(WM_MESSAGE * pMsg) {
//  WM_HWIN hDlg;
//  int NCode;
//  int Id;
//  hDlg = pMsg->hWin;
//  switch (pMsg->MsgId) {
//  case WM_PAINT:
//	  GUI_SetBkColor(GUI_BLUE); //
//      GUI_Clear();
//    break;
//  case WM_INIT_DIALOG:
//   
//    break;
//   case WM_NOTIFY_PARENT:
//    Id    = WM_GetId(pMsg->hWinSrc);
//    NCode = pMsg->Data.v;
//	switch(Id) 
//	{
//      case ID_BUTTON_2DLG_0: // Notifications sent by 'ButKEY'
//         switch(NCode) {
//             case WM_NOTIFICATION_CLICKED: 
//             CreateKeyBoard(hWin[1],160,80,0,23);
//			 break;
//		 }
//         break;     
//    }

//	break;

//  default:
//    WM_DefaultProc(pMsg);
//  }
//}
//---------------------------------------------------------------------

/*
static void _cbDialog1(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'panel'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, 0x00FF8080);
    
    
    break; 
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_1: // Notifications sent by 'svVal'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
//         hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
//         CreateKeyBoard(hFrame,160,80,ID_EDIT_1,EDIT_GetValue(ID_EDIT_1));
        break;
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}


static void _cbDialog1(WM_MESSAGE * pMsg) {
  WM_HWIN hDlg;
  int     NCode;
  int     Id;
  KEY_VALUE *keyvalue;
  hDlg = pMsg->hWin;
  switch (pMsg->MsgId) {
  case WM_PAINT:
//	  GUI_SetBkColor(GUI_RED); //
 //     GUI_Clear();
      
    break;
  case WM_INIT_DIALOG:
     hDlg = WM_GetDialogItem(pMsg->hWin, ID_EDIT_TEXT0);
	EDIT_SetDecMode(hDlg, 0, 0,999999, 1, 0);
    EDIT_SetFont(hDlg, GUI_FONT_32B_1);
    EDIT_SetTextAlign(hDlg, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_SetValue(hDlg,Num);
//  	EDIT_SetSel(hDlg,0, -1);	
 //   WM_CreateTimer(pMsg->hWin, 0, 500, 0); 
    break;
  case WM_TIMER:
	  
  
//	WM_RestartTimer(pMsg->Data.v, 100);
	break;
   
  default:
    WM_DefaultProc(pMsg);
  }
} */
//---------------------------------------------------------------------
//static void _cbDialog4(WM_MESSAGE * pMsg) {
//  WM_HWIN hDlg;

//  hDlg = pMsg->hWin;
//  switch (pMsg->MsgId) {
//  case WM_PAINT:
//  
//	 
//    break;
//  case WM_INIT_DIALOG:
//   
//    break;
//  
//	  
//  default:
//    WM_DefaultProc(pMsg);
//  }
//}
//----------------------------------------------------------------
/*void dspWinIndex(U8 x)
{
	if(x>3) return;
    WM_HideWindow(hFrame);
	WM_HideWindow(hWin[0]);
	WM_HideWindow(hWin[1]);
	WM_HideWindow(hWin[2]);
	WM_HideWindow(hWin[3]);
	WM_ShowWindow(hFrame);
	WM_ShowWindow(hWin[x]);
}*/
void Thermocouple(WM_HWIN hItem,int Item,int id)
{
	hItem = WM_GetDialogItem(hItem, Item);
	if(temperature[id].jk){
		 temperature[id].jk = 0;
		 BUTTON_SetText(hItem, "Thermocouple type J");  
	 }else{
		 temperature[id].jk = 1;
		 BUTTON_SetText(hItem, "Thermocouple type K");  
	 }
}
//-------------------------------------------------------------
char* int2Text(int data)
{
	static char str[5];
	str[0]=(char)(data/1000%10)+0x30;
	str[1]=(char)(data/100%10)+0x30;
	str[2]=(char)(data/10%10)+0x30;
	str[3]='.';
	str[4]=(char)(data%10)+0x30;
	return str;
}
//---------------------------------------------------------------
void TemperaturePV(WM_HWIN hItem,int Item,int id)
{
	hItem = WM_GetDialogItem(hItem, Item);
	TEXT_SetText(hItem, int2Text(temperature[id].PV10));
	if(temperature[id].alarm) TEXT_SetTextColor(hItem, GUI_RED);	
	else TEXT_SetTextColor(hItem, 0x00408000);		
}
//---------------------------------------------------------------
void TemperatureSV(WM_HWIN hItem,int Item,int id)
{		
	hItem = WM_GetDialogItem(hItem,Item);
    EDIT_SetValue(hItem, temperature[id].SV10);
}
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  KEY_VALUE *keyvalue;
	
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	  
    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, GUI_FONT_32B_1);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetText(hItem, "Leak adhesive sensor");
    FRAMEWIN_SetTextColor(hItem, 0x00800040);
    hWin = WM_GetClientWindow(hItem);
//--------------------------------------------------------------------
    // Initialization of 'id'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_A0); 
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "NO.1");
    TEXT_SetTextColor(hItem, 0x00FFFFFF);

    // Initialization of 'pvVal'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_A0);
    EDIT_SetFont(hItem, GUI_FONT_D32);
    WM_DisableWindow(hItem);
  
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_A4);
    TEXT_SetFont(hItem, GUI_FONT_D32);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	 
    // Initialization of 'PV'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_A1);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetTextColor(hItem, 0x00FF8000);

    // Initialization of 'pt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_A2);
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "C");
	TEXT_SetTextColor(hItem, 0x00408000);

    // Initialization of 'o'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_A3);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
	TEXT_SetTextColor(hItem, 0x00408000);

    // Initialization of 'svVal'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_A1);
	EDIT_SetDecMode(hItem, 0, 0,9999, 1, 0);
    EDIT_SetFont(hItem, GUI_FONT_32B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, 0x00FF0080);

    // Initialization of 'JK'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_A);
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
	Thermocouple(pMsg->hWin,ID_BUTTON_A,0);

    // Initialization of 'SV'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_A5);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetText(hItem, "SV");
    TEXT_SetTextColor(hItem, 0x00FF8000);

    // Initialization of 'o'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_A6);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, 0x00FF0080);

    // Initialization of 'pt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_A7);
    TEXT_SetText(hItem, "C");
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetTextColor(hItem, 0x00FF0080);  
//--------------------------------------------------------------------
    // Initialization of 'id'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_B0); 
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "NO.2");
    TEXT_SetTextColor(hItem, 0x00FFFFFF);

    // Initialization of 'pvVal'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_B0);
    EDIT_SetFont(hItem, GUI_FONT_D32);
    WM_DisableWindow(hItem);
  
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_B4);
    TEXT_SetFont(hItem, GUI_FONT_D32);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    
    // Initialization of 'PV'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_B1);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetTextColor(hItem, 0x00FF8000);

    // Initialization of 'pt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_B2);
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "C");
	TEXT_SetTextColor(hItem, 0x00408000);

    // Initialization of 'o'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_B3);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
	TEXT_SetTextColor(hItem, 0x00408000);

    // Initialization of 'svVal'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_B1);
	EDIT_SetDecMode(hItem, 0, 0,9999, 1, 0);
    EDIT_SetFont(hItem, GUI_FONT_32B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, 0x00FF0080);

    // Initialization of 'JK'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_B);
    Thermocouple(pMsg->hWin,ID_BUTTON_B,1);
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);

    // Initialization of 'SV'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_B5);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetText(hItem, "SV");
    TEXT_SetTextColor(hItem, 0x00FF8000);

    // Initialization of 'o'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_B6);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, 0x00FF0080);

    // Initialization of 'pt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_B7);
    TEXT_SetText(hItem, "C");
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetTextColor(hItem, 0x00FF0080);  
	
//--------------------------------------------------------------------
    // Initialization of 'id'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_C0); 
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "NO.3");
    TEXT_SetTextColor(hItem, 0x00FFFFFF);

    // Initialization of 'pvVal'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_C0);
    EDIT_SetFont(hItem, GUI_FONT_D32);
    WM_DisableWindow(hItem);
  
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_C4);
    TEXT_SetFont(hItem, GUI_FONT_D32);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    
    // Initialization of 'PV'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_C1);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetTextColor(hItem, 0x00FF8000);

    // Initialization of 'pt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_C2);
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "C");
	TEXT_SetTextColor(hItem, 0x00408000);

    // Initialization of 'o'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_C3);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
	TEXT_SetTextColor(hItem, 0x00408000);

    // Initialization of 'svVal'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_C1);
	EDIT_SetDecMode(hItem, 0, 0,9999, 1, 0);
    EDIT_SetFont(hItem, GUI_FONT_32B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, 0x00FF0080);

    // Initialization of 'JK'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_C);
    Thermocouple(pMsg->hWin,ID_BUTTON_C,2);
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);

    // Initialization of 'SV'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_C5);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetText(hItem, "SV");
    TEXT_SetTextColor(hItem, 0x00FF8000);

    // Initialization of 'o'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_C6);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, 0x00FF0080);

    // Initialization of 'pt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_C7);
    TEXT_SetText(hItem, "C");
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetTextColor(hItem, 0x00FF0080);  	
//--------------------------------------------------------------------
    // Initialization of 'id'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_D0); 
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "NO.4");
    TEXT_SetTextColor(hItem, 0x00FFFFFF);

    // Initialization of 'pvVal'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_D0);
    EDIT_SetFont(hItem, GUI_FONT_D32);
    WM_DisableWindow(hItem);
  
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_D4);
    TEXT_SetFont(hItem, GUI_FONT_D32);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    
    // Initialization of 'PV'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_D1);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetTextColor(hItem, 0x00FF8000);

    // Initialization of 'pt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_D2);
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "C");
	TEXT_SetTextColor(hItem, 0x00408000);

    // Initialization of 'o'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_D3);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
	TEXT_SetTextColor(hItem, 0x00408000);

    // Initialization of 'svVal'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_D1);
	EDIT_SetDecMode(hItem, 0, 0,9999, 1, 0);
    EDIT_SetFont(hItem, GUI_FONT_32B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, 0x00FF0080);

    // Initialization of 'JK'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_D);
    Thermocouple(pMsg->hWin,ID_BUTTON_D,3);
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);

    // Initialization of 'SV'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_D5);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetText(hItem, "SV");
    TEXT_SetTextColor(hItem, 0x00FF8000);

    // Initialization of 'o'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_D6);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, 0x00FF0080);

    // Initialization of 'pt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_D7);
    TEXT_SetText(hItem, "C");
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetTextColor(hItem, 0x00FF0080);  	
//--------------------------------------------------------------------
    // Initialization of 'id'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_E0); 
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "NO.5");
    TEXT_SetTextColor(hItem, 0x00FFFFFF);

    // Initialization of 'pvVal'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_E0);
    EDIT_SetFont(hItem, GUI_FONT_D32);
    WM_DisableWindow(hItem);
  
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_E4);
    TEXT_SetFont(hItem, GUI_FONT_D32);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    
    // Initialization of 'PV'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_E1);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetTextColor(hItem, 0x00FF8000);

    // Initialization of 'pt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_E2);
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "C");
	TEXT_SetTextColor(hItem, 0x00408000);

    // Initialization of 'o'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_E3);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
	TEXT_SetTextColor(hItem, 0x00408000);

    // Initialization of 'svVal'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_E1);
	EDIT_SetDecMode(hItem, 0, 0,9999, 1, 0);
    EDIT_SetFont(hItem, GUI_FONT_32B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, 0x00FF0080);

    // Initialization of 'JK'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_E);
    Thermocouple(pMsg->hWin,ID_BUTTON_E,4);
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);

    // Initialization of 'SV'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_E5);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetText(hItem, "SV");
    TEXT_SetTextColor(hItem, 0x00FF8000);

    // Initialization of 'o'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_E6);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, 0x00FF0080);

    // Initialization of 'pt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_E7);
    TEXT_SetText(hItem, "C");
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetTextColor(hItem, 0x00FF0080);  	
//--------------------------------------------------------------------
    // Initialization of 'id'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_F0); 
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "NO.6");
    TEXT_SetTextColor(hItem, 0x00FFFFFF);

    // Initialization of 'pvVal'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_F0);
    EDIT_SetFont(hItem, GUI_FONT_D32);
    WM_DisableWindow(hItem);
  
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_F4);
    TEXT_SetFont(hItem, GUI_FONT_D32);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    
    // Initialization of 'PV'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_F1);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetTextColor(hItem, 0x00FF8000);

    // Initialization of 'pt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_F2);
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "C");
	TEXT_SetTextColor(hItem, 0x00408000);

    // Initialization of 'o'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_F3);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
	TEXT_SetTextColor(hItem, 0x00408000);

    // Initialization of 'svVal'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_F1);
	EDIT_SetDecMode(hItem, 0, 0,9999, 1, 0);
    EDIT_SetFont(hItem, GUI_FONT_32B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, 0x00FF0080);

    // Initialization of 'JK'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_F);
    Thermocouple(pMsg->hWin,ID_BUTTON_F,5);
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);

    // Initialization of 'SV'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_F5);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetText(hItem, "SV");
    TEXT_SetTextColor(hItem, 0x00FF8000);

    // Initialization of 'o'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_F6);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, 0x00FF0080);

    // Initialization of 'pt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_F7);
    TEXT_SetText(hItem, "C");
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetTextColor(hItem, 0x00FF0080);  
//--------------------------------------------------------------------
    // Initialization of 'id'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_G0); 
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "NO.7");
    TEXT_SetTextColor(hItem, 0x00FFFFFF);

    // Initialization of 'pvVal'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_G0);
    EDIT_SetFont(hItem, GUI_FONT_D32);
    WM_DisableWindow(hItem);
  
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_G4);
    TEXT_SetFont(hItem, GUI_FONT_D32);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    
    // Initialization of 'PV'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_G1);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetTextColor(hItem, 0x00FF8000);

    // Initialization of 'pt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_G2);
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "C");
	TEXT_SetTextColor(hItem, 0x00408000);

    // Initialization of 'o'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_G3);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
	TEXT_SetTextColor(hItem, 0x00408000);

    // Initialization of 'svVal'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_G1);
	EDIT_SetDecMode(hItem, 0, 0,9999, 1, 0);
    EDIT_SetFont(hItem, GUI_FONT_32B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, 0x00FF0080);

    // Initialization of 'JK'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_G);
    Thermocouple(pMsg->hWin,ID_BUTTON_G,6);
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);

    // Initialization of 'SV'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_G5);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetText(hItem, "SV");
    TEXT_SetTextColor(hItem, 0x00FF8000);

    // Initialization of 'o'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_G6);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, 0x00FF0080);

    // Initialization of 'pt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_G7);
    TEXT_SetText(hItem, "C");
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetTextColor(hItem, 0x00FF0080);  
//--------------------------------------------------------------------
    // Initialization of 'id'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_H0); 
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "NO.8");
    TEXT_SetTextColor(hItem, 0x00FFFFFF);

    // Initialization of 'pvVal'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_H0);
    EDIT_SetFont(hItem, GUI_FONT_D32);
    WM_DisableWindow(hItem);
  
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_H4);
    TEXT_SetFont(hItem, GUI_FONT_D32);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    
    // Initialization of 'PV'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_H1);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetTextColor(hItem, 0x00FF8000);

    // Initialization of 'pt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_H2);
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "C");
	TEXT_SetTextColor(hItem, 0x00408000);

    // Initialization of 'o'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_H3);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
	TEXT_SetTextColor(hItem, 0x00408000);

    // Initialization of 'svVal'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_H1);
	EDIT_SetDecMode(hItem, 0, 0,9999, 1, 0);
    EDIT_SetFont(hItem, GUI_FONT_32B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, 0x00FF0080);

    // Initialization of 'JK'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_H);
    Thermocouple(pMsg->hWin,ID_BUTTON_H,7);
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);

    // Initialization of 'SV'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_H5);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetText(hItem, "SV");
    TEXT_SetTextColor(hItem, 0x00FF8000);

    // Initialization of 'o'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_H6);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, 0x00FF0080);

    // Initialization of 'pt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_H7);
    TEXT_SetText(hItem, "C");
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetTextColor(hItem, 0x00FF0080);  	
    break;
  case WM_PAINT:	
	GUI_DrawGradientV(0, 0, 720, 480, 0x8080FF, GUI_DARKGREEN);
    GUI_SetColor(0x00FF8080);
	GUI_FillRect(5,  12,5+166,  12+196); 
    GUI_FillRect(181,12,181+166,12+196); 
    GUI_FillRect(359,12,359+166,12+196); 
    GUI_FillRect(537,12,537+166,12+196); 
  
    GUI_FillRect(5,  230,5+166,  230+196); 
    GUI_FillRect(181,230,181+166,230+196); 
    GUI_FillRect(359,230,359+166,230+196); 
    GUI_FillRect(537,230,537+166,230+196);   
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {		
    case ID_EDIT_A1:   //'svVal'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 		 
         hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_A1);
         CreateKeyBoard(hWin,163,0,ID_EDIT_A1,EDIT_GetValue(hItem));   
         break;    
      }
      break;
	case ID_EDIT_B1:   //'svVal'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 		 
         hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_B1);
         CreateKeyBoard(hWin,341,0,ID_EDIT_B1,EDIT_GetValue(hItem));   
         break;    
      }
      break;
   case ID_EDIT_C1:   //'svVal'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 		 
         hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_C1);
         CreateKeyBoard(hWin,128,0,ID_EDIT_C1,EDIT_GetValue(hItem));   
         break;    
      }
      break;	  
   case ID_EDIT_D1:   //'svVal'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 		 
         hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_D1);
         CreateKeyBoard(hWin,333,0,ID_EDIT_D1,EDIT_GetValue(hItem));   
         break;    
      }
      break;
    case ID_EDIT_E1:   //'svVal'//////////
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 		 
         hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_E1);
         CreateKeyBoard(hWin,163,118,ID_EDIT_E1,EDIT_GetValue(hItem));   
         break;    
      }
      break;
	case ID_EDIT_F1:   //'svVal'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 		 
         hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_F1);
         CreateKeyBoard(hWin,341,118,ID_EDIT_F1,EDIT_GetValue(hItem));   
         break;    
      }
      break;
   case ID_EDIT_G1:   //'svVal'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 		 
         hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_G1);
         CreateKeyBoard(hWin,128,118,ID_EDIT_G1,EDIT_GetValue(hItem));   
         break;    
      }
      break;	  
   case ID_EDIT_H1:   //'svVal'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 		 
         hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_H1);
         CreateKeyBoard(hWin,333,118,ID_EDIT_H1,EDIT_GetValue(hItem));   
         break;    
      }
      break;	  
//------------------------------------------------
   case ID_BUTTON_A:   //'JK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 		 
         Thermocouple(pMsg->hWin,ID_BUTTON_A,0);
         break;    
      }
      break;
   case ID_BUTTON_B:   //'JK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 		 
         Thermocouple(pMsg->hWin,ID_BUTTON_B,1);
         break;    
      }
      break;
   case ID_BUTTON_C:   //'JK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 		 
         Thermocouple(pMsg->hWin,ID_BUTTON_C,2);
         break;    
      }
      break;
   case ID_BUTTON_D:   //'JK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 		 
         Thermocouple(pMsg->hWin,ID_BUTTON_D,3);
         break;    
      }
      break;
   case ID_BUTTON_E:   //'JK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 		 
         Thermocouple(pMsg->hWin,ID_BUTTON_E,4);
         break;    
      }
      break;	  
   case ID_BUTTON_F:   //'JK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 		 
         Thermocouple(pMsg->hWin,ID_BUTTON_F,5);
         break;    
      }
      break;	
   case ID_BUTTON_G:   //'JK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 		 
         Thermocouple(pMsg->hWin,ID_BUTTON_G,6);
         break;    
      }
      break;
   case ID_BUTTON_H:   //'JK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 		 
         Thermocouple(pMsg->hWin,ID_BUTTON_H,7);
         break;    
      }
      break;	  
   	  
    }
    break;
	case KEY_MSG:  //WM_USER:
		keyvalue = (KEY_VALUE*)pMsg->Data.p;
	    switch(keyvalue->key) {
			case ID_EDIT_A1:		
            temperature[0].SV10 = keyvalue->value;			
			TemperatureSV(pMsg->hWin,ID_EDIT_A1,0);
			break;
  
			case ID_EDIT_B1:					
			temperature[1].SV10 = keyvalue->value;			
			TemperatureSV(pMsg->hWin,ID_EDIT_B1,1);
			break; 

			case ID_EDIT_C1:					
			temperature[2].SV10 = keyvalue->value;			
			TemperatureSV(pMsg->hWin,ID_EDIT_C1,2);
			break;

			case ID_EDIT_D1:					
			temperature[3].SV10 = keyvalue->value;			
			TemperatureSV(pMsg->hWin,ID_EDIT_D1,3);
			break;

			case ID_EDIT_E1:					
			temperature[4].SV10 = keyvalue->value;			
			TemperatureSV(pMsg->hWin,ID_EDIT_E1,4);
			break;

			case ID_EDIT_F1:					
			temperature[5].SV10 = keyvalue->value;			
			TemperatureSV(pMsg->hWin,ID_EDIT_F1,5);
			break;

			case ID_EDIT_G1:					
			temperature[6].SV10 = keyvalue->value;			
			TemperatureSV(pMsg->hWin,ID_EDIT_G1,6);
			break;

			case ID_EDIT_H1:				
			temperature[7].SV10 = keyvalue->value;			
			TemperatureSV(pMsg->hWin,ID_EDIT_H1,7);
			break;
	  }					
	  break;	
	case UPDATA_DLG:
        TemperaturePV(pMsg->hWin,ID_TEXT_A4,0);	
	    TemperatureSV(pMsg->hWin,ID_EDIT_A1,0);
	
	    TemperaturePV(pMsg->hWin,ID_TEXT_B4,1);
        TemperatureSV(pMsg->hWin,ID_EDIT_B1,1);	
	
	    TemperaturePV(pMsg->hWin,ID_TEXT_C4,2);	
	    TemperatureSV(pMsg->hWin,ID_EDIT_C1,2);
	
	    TemperaturePV(pMsg->hWin,ID_TEXT_D4,3);	
	    TemperatureSV(pMsg->hWin,ID_EDIT_D1,3);
	
	    TemperaturePV(pMsg->hWin,ID_TEXT_E4,4);	
        TemperatureSV(pMsg->hWin,ID_EDIT_E1,4);
	
	    TemperaturePV(pMsg->hWin,ID_TEXT_F4,5);	
	    TemperatureSV(pMsg->hWin,ID_EDIT_F1,5);
	
	    TemperaturePV(pMsg->hWin,ID_TEXT_G4,6);	
	    TemperatureSV(pMsg->hWin,ID_EDIT_G1,6);
	
	    TemperaturePV(pMsg->hWin,ID_TEXT_H4,7);
		TemperatureSV(pMsg->hWin,ID_EDIT_H1,7);
    break;		
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Creategraph
*/

void Creategraph(void) {

  hFrame = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  WM_HideWindow(hFrame);
}

void dispTemPanel(void) {
	if(graph) {
//		GUI_Delay(200);
	//	for(int i=0;i<8;i++)
	//	temperature[i].alarm = (temperature[i].PV10 > temperature[i].SV10) ? 1 : 0;
		WM_SendMessageNoPara(hWin, UPDATA_DLG);		
		GUI_Exec1();
	}
}
// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
