/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/


// USER START (Optionally insert additional defines)
  
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "keyboard", ID_FRAMEKEY, 3, 1, 232, 319, FRAMEWIN_CF_MOVEABLE, 0x0, 0 },
  { BUTTON_CreateIndirect, "ButC", ID_BUTTON_KEY9, 3, 229, 70, 50, 0, 0x0, 0 },
  { EDIT_CreateIndirect,   "Edit", ID_EDIT_KEY0, 1, 2, 155, 61, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "But7", ID_BUTTON_KEY0, 3, 70, 70, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "But8", ID_BUTTON_KEY1, 76, 70, 70, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "But9", ID_BUTTON_KEY2, 149, 70, 70, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "But4", ID_BUTTON_KEY3, 3, 123, 70, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "But5", ID_BUTTON_KEY4, 76, 123, 70, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "But6", ID_BUTTON_KEY5, 149, 123, 70, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "But1", ID_BUTTON_KEY6, 3, 176, 70, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "But2", ID_BUTTON_KEY7, 76, 176, 70, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "But3", ID_BUTTON_KEY8, 149, 176, 70, 50, 0, 0x0, 0 },  
  { BUTTON_CreateIndirect, "But0", ID_BUTTON_KEY10, 76, 229, 70, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ButOK", ID_BUTTON_KEY11, 149, 229, 70, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "But+", ID_BUTTON_KEY12, 159, 3, 60, 28, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "But-", ID_BUTTON_KEY13, 159, 35, 60, 28, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static int     Number;
static int     adj;
static WM_MESSAGE Msg;
static KEY_VALUE keyvalue;
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  	
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:	  
    //
    // Initialization of 'keyboard'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetText(hItem, " range: 0.0-999.9");
    FRAMEWIN_SetFont(hItem, GUI_FONT_20B_1);
    FRAMEWIN_SetTitleHeight(hItem, 30);
	FRAMEWIN_AddCloseButton(hItem, FRAMEWIN_BUTTON_RIGHT,0);
  
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_KEY0);
	EDIT_SetDecMode(hItem, 0, 0,9999, 1, 0);
    EDIT_SetFont(hItem, &GUI_FontD32);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_SetValue(hItem,Number);
    WM_DisableWindow(hItem);
    //
    // Initialization of 'But7'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_KEY0);
    BUTTON_SetText(hItem, "7");
    BUTTON_SetFont(hItem, GUI_FONT_32B_1);
    //
    // Initialization of 'But8'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_KEY1);
    BUTTON_SetText(hItem, "8");
    BUTTON_SetFont(hItem, GUI_FONT_32B_1);
    //
    // Initialization of 'But9'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_KEY2);
    BUTTON_SetText(hItem, "9");
    BUTTON_SetFont(hItem, GUI_FONT_32B_1);
    //
    // Initialization of 'But4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_KEY3);
    BUTTON_SetText(hItem, "4");
    BUTTON_SetFont(hItem, GUI_FONT_32B_1);
    //
    // Initialization of 'But5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_KEY4);
    BUTTON_SetText(hItem, "5");
    BUTTON_SetFont(hItem, GUI_FONT_32B_1);
    //
    // Initialization of 'But6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_KEY5);
    BUTTON_SetText(hItem, "6");
    BUTTON_SetFont(hItem, GUI_FONT_32B_1);
    //
    // Initialization of 'But1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_KEY6);
    BUTTON_SetText(hItem, "1");
    BUTTON_SetFont(hItem, GUI_FONT_32B_1);
    //
    // Initialization of 'But2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_KEY7);
    BUTTON_SetText(hItem, "2");
    BUTTON_SetFont(hItem, GUI_FONT_32B_1);
    //
    // Initialization of 'But3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_KEY8);
    BUTTON_SetText(hItem, "3");
    BUTTON_SetFont(hItem, GUI_FONT_32B_1);
    //
    // Initialization of 'ButC'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_KEY9);
    BUTTON_SetText(hItem, "Clear");
    BUTTON_SetFont(hItem, GUI_FONT_24B_1);
    //
    // Initialization of 'But0'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_KEY10);
    BUTTON_SetText(hItem, "0");
    BUTTON_SetFont(hItem, GUI_FONT_32B_1);
    //
    // Initialization of 'ButOK'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_KEY11);
    BUTTON_SetText(hItem, "Enter");
    BUTTON_SetFont(hItem, GUI_FONT_24B_1);  
    //
    // Initialization of '+'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_KEY12);
    BUTTON_SetText(hItem, "+");
    BUTTON_SetFont(hItem, GUI_FONT_32B_1);  
	
	//
    // Initialization of '-'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_KEY13);
    BUTTON_SetText(hItem, "-");
    BUTTON_SetFont(hItem, GUI_FONT_32B_1);  
    break;
  case WM_NOTIFY_PARENT:

    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_KEY0);
    switch(Id) {
		
    case ID_BUTTON_KEY0: // Notifications sent by 'But7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 		  
	     if(!adj) {Number = 0; adj = 1;}
         Number *= 10;
		 Number += 7;	
		 if(Number>9999) Number =0;
		 EDIT_SetValue(hItem,Number);
        break;    
      }
      break;
    case ID_BUTTON_KEY1: // Notifications sent by 'But8'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
	     if(!adj) {Number = 0; adj = 1;}
         Number *= 10;
		 Number += 8;
		 if(Number>9999) Number =0;
		 EDIT_SetValue(hItem,Number);
        break;
      }
      break;
    case ID_BUTTON_KEY2: // Notifications sent by 'But9'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
	     if(!adj) {Number = 0; adj = 1;}
         Number *= 10;
		 Number += 9;	
		 if(Number>9999) Number =0;
		 EDIT_SetValue(hItem,Number);
        break;
      }
      break;
    case ID_BUTTON_KEY3: // Notifications sent by 'But4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
	     if(!adj) {Number = 0; adj = 1;}
         Number *= 10;
		 Number += 4;	
		 if(Number>9999) Number =0;
		 EDIT_SetValue(hItem,Number);
        break;
      }
      break;
    case ID_BUTTON_KEY4: // Notifications sent by 'But5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
	     if(!adj) {Number = 0; adj = 1;}
         Number *= 10;
		 Number += 5;	
		 if(Number>9999) Number =0;
		 EDIT_SetValue(hItem,Number);
        break;
      }
      break;
    case ID_BUTTON_KEY5: // Notifications sent by 'But6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
	     if(!adj) {Number = 0; adj = 1;}
         Number *= 10;
		 Number += 6;	
		 if(Number>9999) Number =0;
		 EDIT_SetValue(hItem,Number);
        break;
      }
      break;
    case ID_BUTTON_KEY6: // Notifications sent by 'But1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
	     if(!adj) {Number = 0; adj = 1;}
         Number *= 10;
		 Number += 1;	
		 if(Number>9999) Number =0;
		 EDIT_SetValue(hItem,Number);
        break;
      }
      break;
    case ID_BUTTON_KEY7: // Notifications sent by 'But2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
	     if(!adj) {Number = 0; adj = 1;}
         Number *= 10;
		 Number += 2;	
		 if(Number>9999) Number =0;
		 EDIT_SetValue(hItem,Number);
        break;
      }
      break;
    case ID_BUTTON_KEY8: // Notifications sent by 'But3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
	    if(!adj) {Number = 0; adj = 1;}
        Number *= 10;
		 Number += 3;	
		 if(Number>9999) Number =0;
		 EDIT_SetValue(hItem,Number);
        break;
      }
      break;
    case ID_BUTTON_KEY9: // Notifications sent by 'ButC'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
         Number = 0;	
		 EDIT_SetValue(hItem,Number);
        break;
      }
      break;
    case ID_BUTTON_KEY10: // Notifications sent by 'But0'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
	     if(!adj) {Number = 0; adj = 1;}
         Number *= 10;
		 Number += 0;	
		 if(Number>9999) Number =0;
		 EDIT_SetValue(hItem,Number);
        break;
      }
      break;
    case ID_BUTTON_KEY11: // Notifications sent by 'ButOK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
	    keyvalue.value = Number;
		WM_SendToParent(pMsg->hWin, &Msg);  
        GUI_EndDialog(pMsg->hWin, 0);
	    
        break;
      }
      break;
    case ID_BUTTON_KEY12: // Notifications sent by '+'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
         adj = 1;      
		 if(Number<9999) Number ++;
		 EDIT_SetValue(hItem,Number);
        break;
      }
      break;  
   case ID_BUTTON_KEY13: // Notifications sent by '-'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
	     adj = 1;
         if(Number>0) Number --;
		 EDIT_SetValue(hItem,Number);
        break;
      }
      break;  
	  
	  
    }
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/

void CreateKeyBoard(WM_HWIN hParent,int x0,int y0,int keyindex,int value) {   
	static WM_HWIN hKey;		
	if(!WM_IsWindow(hKey)){
		Number = value;
		adj = 0;	
        keyvalue.key = keyindex;
		keyvalue.value = 0;
		
        hKey = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, hParent, x0, y0);
	    WM_MakeModal(hKey);
		
		Msg.MsgId = KEY_MSG;
		Msg.hWin = hParent;
		Msg.hWinSrc = hKey;
		Msg.Data.p = &keyvalue;
	}
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
