/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
void DspSide(void);
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 720, 0,   80, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "graph",  ID_BUTTON_0, 5,   40,  70, 40,  0, 0x0, 0 },
  { BUTTON_CreateIndirect, "panel",  ID_BUTTON_1, 5,   120, 70, 40,  0, 0x0, 0 },
 // { BUTTON_CreateIndirect, "text",   ID_BUTTON_2, 5,   200, 70, 40,  0, 0x0, 0 },
 // { BUTTON_CreateIndirect, "seting", ID_BUTTON_3, 5,   280, 70, 40,  0, 0x0, 0 },
 // { BUTTON_CreateIndirect, "history",ID_BUTTON_4, 5,   360, 70, 40,  0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_PAINT:
	  DspSide();

     break;

  case WM_INIT_DIALOG:
	   
	   //
    // Initialization of 'graph'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_24_1);
    //
    // Initialization of 'panel'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_24_1);
    //
    // Initialization of 'text'
    //
  //  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
  //  BUTTON_SetFont(hItem, GUI_FONT_24_1);
    //
    // Initialization of 'seting'
    //
  //  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
  //  BUTTON_SetFont(hItem, GUI_FONT_24_1);
    //
    // Initialization of 'history'
    //
  //  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
  //  BUTTON_SetFont(hItem, GUI_FONT_24_1);
	  break;
   case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'graph'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 
        if(winId){		  
			reDraw=1;
			graph=0;
			winId=0;
			WM_HideWindow(hFrame);
		}
        break;     
      }
      break;
   case ID_BUTTON_1: // Notifications sent by 'panel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:  
		  if(winId !=1){
			graph=1;
			winId = 1;
			GUI_Clear(); 
			WM_ShowWindow(hFrame);
		  }
        break;     
      }
      break;
 /* case ID_BUTTON_2: // Notifications sent by 'text'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:  
		  if(winId !=2){
			graph=1;
			winId = 2;			
			GUI_Clear(); 
			dspWinIndex(1); 
		  }
        break;     
      }
      break;
   case ID_BUTTON_3: // Notifications sent by 'seting'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:      
       if(winId !=3){
			graph=1;
			winId = 3;
			GUI_Clear(); 
			dspWinIndex(2); 
		  }
        break;     
      }
      break;
  case ID_BUTTON_4: // Notifications sent by 'history'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:      
        if(winId !=4){
			graph=1;
			winId = 4;
			GUI_Clear(); 
			dspWinIndex(3);
		  }
        break;     
      }
      break;
    */
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

void CreateWindow(void) {  
   GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
